"""Catalog of NVIDIA NIM chat models, validated live against the API."""

NVIDIA_MODELS = [
    {
        "id": 'abacusai/dracarys-llama-3.1-70b-instruct',
        "name": 'Dracarys Llama 3.1 70B Instruct',
        "vendor": 'AbacusAI',
        "description": 'AbacusAI fine-tune of Llama 3.1 70B optimized for coding tasks.',
        "context": 128000,
    },
    {
        "id": 'bytedance/seed-oss-36b-instruct',
        "name": 'Seed Oss 36B Instruct',
        "vendor": 'ByteDance',
        "description": 'ByteDance open-source 36B instruct model.',
        "context": 32768,
    },
    {
        "id": 'google/gemma-3-12b-it',
        "name": 'Gemma 3 12B It',
        "vendor": 'Google',
        "description": 'Google Gemma 3 12B instruction-tuned, multimodal.',
        "context": 128000,
    },
    {
        "id": 'google/gemma-3-27b-it',
        "name": 'Gemma 3 27B It',
        "vendor": 'Google',
        "description": 'Google Gemma 3 27B instruction-tuned, multimodal.',
        "context": 128000,
    },
    {
        "id": 'google/gemma-3-4b-it',
        "name": 'Gemma 3 4B It',
        "vendor": 'Google',
        "description": 'Google Gemma 3 4B instruction-tuned, multimodal.',
        "context": 128000,
    },
    {
        "id": 'google/gemma-3n-e2b-it',
        "name": 'Gemma 3N E2B It',
        "vendor": 'Google',
        "description": 'Google Gemma 3n E2B — efficient on-device class.',
        "context": 128000,
    },
    {
        "id": 'google/gemma-3n-e4b-it',
        "name": 'Gemma 3N E4B It',
        "vendor": 'Google',
        "description": 'Google Gemma 3n E4B — efficient on-device class.',
        "context": 128000,
    },
    {
        "id": 'meta/llama-3.1-405b-instruct',
        "name": 'Llama 3.1 405B Instruct',
        "vendor": 'Meta',
        "description": 'Meta Llama 3.1 405B — flagship dense LLM.',
        "context": 128000,
    },
    {
        "id": 'meta/llama-3.1-70b-instruct',
        "name": 'Llama 3.1 70B Instruct',
        "vendor": 'Meta',
        "description": 'Meta Llama 3.1 70B Instruct.',
        "context": 128000,
    },
    {
        "id": 'meta/llama-3.1-8b-instruct',
        "name": 'Llama 3.1 8B Instruct',
        "vendor": 'Meta',
        "description": 'Meta Llama 3.1 8B Instruct — fast general-purpose.',
        "context": 128000,
    },
    {
        "id": 'meta/llama-3.2-11b-vision-instruct',
        "name": 'Llama 3.2 11B Vision Instruct',
        "vendor": 'Meta',
        "description": 'Meta Llama 3.2 11B Vision Instruct.',
        "context": 128000,
    },
    {
        "id": 'meta/llama-3.2-1b-instruct',
        "name": 'Llama 3.2 1B Instruct',
        "vendor": 'Meta',
        "description": 'Meta Llama 3.2 1B — tiny edge model.',
        "context": 128000,
    },
    {
        "id": 'meta/llama-3.2-3b-instruct',
        "name": 'Llama 3.2 3B Instruct',
        "vendor": 'Meta',
        "description": 'Meta Llama 3.2 3B — small efficient model.',
        "context": 128000,
    },
    {
        "id": 'meta/llama-3.2-90b-vision-instruct',
        "name": 'Llama 3.2 90B Vision Instruct',
        "vendor": 'Meta',
        "description": 'Meta Llama 3.2 90B Vision — large multimodal.',
        "context": 128000,
    },
    {
        "id": 'meta/llama-3.3-70b-instruct',
        "name": 'Llama 3.3 70B Instruct',
        "vendor": 'Meta',
        "description": 'Meta Llama 3.3 70B — improved reasoning over 3.1.',
        "context": 128000,
    },
    {
        "id": 'meta/llama-4-maverick-17b-128e-instruct',
        "name": 'Llama 4 Maverick 17B 128E Instruct',
        "vendor": 'Meta',
        "description": 'Meta Llama 4 Maverick 17B/128E MoE.',
        "context": 1000000,
    },
    {
        "id": 'meta/llama-guard-4-12b',
        "name": 'Llama Guard 4 12B',
        "vendor": 'Meta',
        "description": 'Meta Llama Guard 4 — safety classifier.',
        "context": 32768,
    },
    {
        "id": 'microsoft/phi-4-mini-instruct',
        "name": 'Phi 4 Mini Instruct',
        "vendor": 'Microsoft',
        "description": 'Microsoft Phi-4 Mini — compact reasoning model.',
        "context": 128000,
    },
    {
        "id": 'minimaxai/minimax-m2.5',
        "name": 'Minimax M2.5',
        "vendor": 'MiniMax',
        "description": 'MiniMax M2.5 — long-context Chinese/English LLM.',
        "context": 1000000,
    },
    {
        "id": 'mistralai/devstral-2-123b-instruct-2512',
        "name": 'Devstral 2 123B Instruct 2512',
        "vendor": 'Mistral AI',
        "description": 'Mistral Devstral 2 123B — coding focused.',
        "context": 32768,
    },
    {
        "id": 'mistralai/magistral-small-2506',
        "name": 'Magistral Small 2506',
        "vendor": 'Mistral AI',
        "description": 'Mistral Magistral Small — reasoning model.',
        "context": 32768,
    },
    {
        "id": 'mistralai/ministral-14b-instruct-2512',
        "name": 'Ministral 14B Instruct 2512',
        "vendor": 'Mistral AI',
        "description": 'Mistral Ministral 14B — efficient instruct.',
        "context": 32768,
    },
    {
        "id": 'mistralai/mistral-large-3-675b-instruct-2512',
        "name": 'Mistral Large 3 675B Instruct 2512',
        "vendor": 'Mistral AI',
        "description": 'Mistral Large 3 675B — flagship MoE.',
        "context": 131072,
    },
    {
        "id": 'mistralai/mistral-nemotron',
        "name": 'Mistral Nemotron',
        "vendor": 'Mistral AI',
        "description": 'NVIDIA + Mistral collaboration model.',
        "context": 128000,
    },
    {
        "id": 'mistralai/mistral-small-4-119b-2603',
        "name": 'Mistral Small 4 119B 2603',
        "vendor": 'Mistral AI',
        "description": 'Mistral Small 4 119B.',
        "context": 131072,
    },
    {
        "id": 'mistralai/mixtral-8x22b-instruct-v0.1',
        "name": 'Mixtral 8X22B Instruct V0.1',
        "vendor": 'Mistral AI',
        "description": 'Mistral Mixtral 8x22B MoE Instruct.',
        "context": 65536,
    },
    {
        "id": 'mistralai/mixtral-8x7b-instruct-v0.1',
        "name": 'Mixtral 8X7B Instruct V0.1',
        "vendor": 'Mistral AI',
        "description": 'Mistral Mixtral 8x7B MoE Instruct.',
        "context": 32768,
    },
    {
        "id": 'moonshotai/kimi-k2-instruct-0905',
        "name": 'Kimi K2 Instruct 0905',
        "vendor": 'Moonshot AI',
        "description": 'Moonshot Kimi K2 (Sept 2025 release).',
        "context": 128000,
    },
    {
        "id": 'moonshotai/kimi-k2.5',
        "name": 'Kimi K2.5',
        "vendor": 'Moonshot AI',
        "description": 'Moonshot Kimi K2.5 — newest flagship.',
        "context": 128000,
    },
    {
        "id": 'nvidia/ising-calibration-1-35b-a3b',
        "name": 'Ising Calibration 1 35B A3B',
        "vendor": 'NVIDIA',
        "description": 'NVIDIA Ising calibration MoE 35B/A3B.',
        "context": 32768,
    },
    {
        "id": 'nvidia/llama-3.1-nemoguard-8b-content-safety',
        "name": 'Llama 3.1 Nemoguard 8B Content Safety',
        "vendor": 'NVIDIA',
        "description": 'NemoGuard content-safety classifier.',
        "context": 128000,
    },
    {
        "id": 'nvidia/llama-3.1-nemoguard-8b-topic-control',
        "name": 'Llama 3.1 Nemoguard 8B Topic Control',
        "vendor": 'NVIDIA',
        "description": 'NemoGuard topic-control classifier.',
        "context": 128000,
    },
    {
        "id": 'nvidia/llama-3.1-nemotron-nano-8b-v1',
        "name": 'Llama 3.1 Nemotron Nano 8B V1',
        "vendor": 'NVIDIA',
        "description": 'Nemotron Nano 8B — efficient assistant.',
        "context": 128000,
    },
    {
        "id": 'nvidia/llama-3.1-nemotron-nano-vl-8b-v1',
        "name": 'Llama 3.1 Nemotron Nano Vl 8B V1',
        "vendor": 'NVIDIA',
        "description": 'Nemotron Nano VL 8B — vision-language.',
        "context": 128000,
    },
    {
        "id": 'nvidia/llama-3.1-nemotron-safety-guard-8b-v3',
        "name": 'Llama 3.1 Nemotron Safety Guard 8B V3',
        "vendor": 'NVIDIA',
        "description": 'Nemotron safety guard v3.',
        "context": 128000,
    },
    {
        "id": 'nvidia/llama-3.3-nemotron-super-49b-v1',
        "name": 'Llama 3.3 Nemotron Super 49B V1',
        "vendor": 'NVIDIA',
        "description": 'Nemotron Super 49B v1 — strong reasoning.',
        "context": 128000,
    },
    {
        "id": 'nvidia/llama-3.3-nemotron-super-49b-v1.5',
        "name": 'Llama 3.3 Nemotron Super 49B V1.5',
        "vendor": 'NVIDIA',
        "description": 'Nemotron Super 49B v1.5.',
        "context": 128000,
    },
    {
        "id": 'nvidia/nemotron-3-content-safety',
        "name": 'Nemotron 3 Content Safety',
        "vendor": 'NVIDIA',
        "description": 'Nemotron 3 content-safety classifier.',
        "context": 128000,
    },
    {
        "id": 'nvidia/nemotron-3-nano-30b-a3b',
        "name": 'Nemotron 3 Nano 30B A3B',
        "vendor": 'NVIDIA',
        "description": 'Nemotron 3 Nano 30B/A3B MoE.',
        "context": 128000,
    },
    {
        "id": 'nvidia/nemotron-3-super-120b-a12b',
        "name": 'Nemotron 3 Super 120B A12B',
        "vendor": 'NVIDIA',
        "description": 'Nemotron 3 Super 120B/A12B MoE.',
        "context": 128000,
    },
    {
        "id": 'nvidia/nemotron-content-safety-reasoning-4b',
        "name": 'Nemotron Content Safety Reasoning 4B',
        "vendor": 'NVIDIA',
        "description": 'Nemotron 4B safety reasoner.',
        "context": 128000,
    },
    {
        "id": 'nvidia/nemotron-mini-4b-instruct',
        "name": 'Nemotron Mini 4B Instruct',
        "vendor": 'NVIDIA',
        "description": 'Nemotron Mini 4B Instruct.',
        "context": 128000,
    },
    {
        "id": 'nvidia/nemotron-nano-12b-v2-vl',
        "name": 'Nemotron Nano 12B V2 Vl',
        "vendor": 'NVIDIA',
        "description": 'Nemotron Nano 12B v2 VL.',
        "context": 128000,
    },
    {
        "id": 'nvidia/nvidia-nemotron-nano-9b-v2',
        "name": 'Nvidia Nemotron Nano 9B V2',
        "vendor": 'NVIDIA',
        "description": 'NVIDIA Nemotron Nano 9B v2.',
        "context": 128000,
    },
    {
        "id": 'nvidia/riva-translate-4b-instruct-v1.1',
        "name": 'Riva Translate 4B Instruct V1.1',
        "vendor": 'NVIDIA',
        "description": 'NVIDIA Riva Translate 4B v1.1.',
        "context": 32768,
    },
    {
        "id": 'openai/gpt-oss-120b',
        "name": 'Gpt Oss 120B',
        "vendor": 'OpenAI',
        "description": 'OpenAI GPT-OSS 120B — open-weight flagship.',
        "context": 128000,
    },
    {
        "id": 'openai/gpt-oss-20b',
        "name": 'Gpt Oss 20B',
        "vendor": 'OpenAI',
        "description": 'OpenAI GPT-OSS 20B — open-weight efficient.',
        "context": 128000,
    },
    {
        "id": 'qwen/qwen2.5-coder-32b-instruct',
        "name": 'QWEN2.5 Coder 32B Instruct',
        "vendor": 'Alibaba Qwen',
        "description": 'Alibaba Qwen 2.5 Coder 32B.',
        "context": 128000,
    },
    {
        "id": 'qwen/qwen3-coder-480b-a35b-instruct',
        "name": 'QWEN3 Coder 480B A35B Instruct',
        "vendor": 'Alibaba Qwen',
        "description": 'Alibaba Qwen 3 Coder 480B/A35B MoE.',
        "context": 128000,
    },
    {
        "id": 'qwen/qwen3-next-80b-a3b-instruct',
        "name": 'QWEN3 Next 80B A3B Instruct',
        "vendor": 'Alibaba Qwen',
        "description": 'Qwen 3 Next 80B/A3B Instruct.',
        "context": 128000,
    },
    {
        "id": 'qwen/qwen3-next-80b-a3b-thinking',
        "name": 'QWEN3 Next 80B A3B Thinking',
        "vendor": 'Alibaba Qwen',
        "description": 'Qwen 3 Next 80B/A3B Thinking — reasoning.',
        "context": 128000,
    },
    {
        "id": 'qwen/qwen3.5-122b-a10b',
        "name": 'QWEN3.5 122B A10B',
        "vendor": 'Alibaba Qwen',
        "description": 'Qwen 3.5 122B/A10B MoE.',
        "context": 128000,
    },
    {
        "id": 'qwen/qwen3.5-397b-a17b',
        "name": 'QWEN3.5 397B A17B',
        "vendor": 'Alibaba Qwen',
        "description": 'Qwen 3.5 397B/A17B MoE — flagship.',
        "context": 128000,
    },
    {
        "id": 'sarvamai/sarvam-m',
        "name": 'Sarvam M',
        "vendor": 'Sarvam AI',
        "description": 'Sarvam M — Indic-language LLM.',
        "context": 32768,
    },
    {
        "id": 'stepfun-ai/step-3.5-flash',
        "name": 'Step 3.5 Flash',
        "vendor": 'StepFun',
        "description": 'StepFun Step 3.5 Flash.',
        "context": 32768,
    },
    {
        "id": 'stockmark/stockmark-2-100b-instruct',
        "name": 'Stockmark 2 100B Instruct',
        "vendor": 'Stockmark',
        "description": 'Stockmark 2 100B — Japanese-focused.',
        "context": 32768,
    },
    {
        "id": 'upstage/solar-10.7b-instruct',
        "name": 'Solar 10.7B Instruct',
        "vendor": 'Upstage',
        "description": 'Upstage Solar 10.7B Instruct.',
        "context": 4096,
    },
    {
        "id": 'z-ai/glm-5.1',
        "name": 'Glm 5.1',
        "vendor": 'Z.AI',
        "description": 'Z.AI GLM 5.1.',
        "context": 128000,
    },
    {
        "id": 'z-ai/glm4.7',
        "name": 'GLM4.7',
        "vendor": 'Z.AI',
        "description": 'Z.AI GLM 4.7.',
        "context": 128000,
    },
    {
        "id": 'z-ai/glm5',
        "name": 'GLM5',
        "vendor": 'Z.AI',
        "description": 'Z.AI GLM 5 — flagship.',
        "context": 128000,
    },
]

DEFAULT_MODEL_ID = "meta/llama-3.1-8b-instruct"
MODEL_IDS = {m["id"] for m in NVIDIA_MODELS}


# Vision-capable chat models (can accept image_url content blocks).
VISION_MODEL_IDS = {
    'meta/llama-3.2-11b-vision-instruct',
    'meta/llama-3.2-90b-vision-instruct',
    'meta/llama-4-maverick-17b-128e-instruct',
    'meta/llama-4-scout-17b-16e-instruct',
    'nvidia/llama-3.1-nemotron-nano-vl-8b-v1',
    'google/gemma-3-4b-it',
    'google/gemma-3-12b-it',
    'google/gemma-3-27b-it',
}

# Mark vision capability inline so the frontend can disable image upload
# when the user picks a text-only model.
for _m in NVIDIA_MODELS:
    _m['vision'] = _m['id'] in VISION_MODEL_IDS


# Image generation catalog — separate endpoint at NVIDIA_GENAI_BASE/{id}.
IMAGE_GEN_MODELS = [
    {
        'id': 'black-forest-labs/flux.1-schnell',
        'name': 'FLUX.1 schnell',
        'vendor': 'Black Forest Labs',
        'description': 'Fast 4-step distilled FLUX. Best for quick drafts.',
        'default_steps': 4,
        'max_steps': 8,
    },
    {
        'id': 'black-forest-labs/flux.1-dev',
        'name': 'FLUX.1 dev',
        'vendor': 'Black Forest Labs',
        'description': 'Higher-quality FLUX. Slower but more faithful.',
        'default_steps': 28,
        'max_steps': 50,
    },
    {
        'id': 'stabilityai/stable-diffusion-3-medium',
        'name': 'Stable Diffusion 3 Medium',
        'vendor': 'Stability AI',
        'description': 'Stable Diffusion 3 — strong on photorealism.',
        'default_steps': 28,
        'max_steps': 50,
    },
    {
        'id': 'stabilityai/sdxl-turbo',
        'name': 'SDXL Turbo',
        'vendor': 'Stability AI',
        'description': 'One-step SDXL distillation. Fastest option.',
        'default_steps': 1,
        'max_steps': 4,
    },
]
IMAGE_GEN_MODEL_IDS = {m['id'] for m in IMAGE_GEN_MODELS}
DEFAULT_IMAGE_GEN_MODEL_ID = 'black-forest-labs/flux.1-schnell'
