# Generated by Django 6.0.4 on 2026-04-25 20:16

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=chat.models._attachment_path),
        ),
    ]
