# Generated by Django 6.0.4 on 2026-04-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_twofactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactor',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twofactor',
            name='last_totp_step',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twofactor',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twofactor',
            name='secret',
            field=models.CharField(max_length=256),
        ),
    ]
