# Generated by Django 6.0.4 on 2026-07-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_twofactor_failed_attempts_twofactor_last_totp_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='max_tokens',
            field=models.PositiveIntegerField(default=1024),
        ),
        migrations.AddField(
            model_name='conversation',
            name='system_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='conversation',
            name='temperature',
            field=models.FloatField(default=0.7),
        ),
    ]
