# Generated by Django 6.0.8 on 2026-10-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_conversation_max_tokens_conversation_system_prompt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('chat_requests', models.PositiveIntegerField(default=0)),
                ('image_requests', models.PositiveIntegerField(default=0)),
                ('prompt_characters', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('chat_requests', models.PositiveIntegerField(default=0)),
                ('image_requests', models.PositiveIntegerField(default=0)),
                ('prompt_characters', models.PositiveBigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_ai_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['day'], name='chat_dailya_day_d68e8b_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'day'), name='unique_daily_ai_usage')],
            },
        ),
    ]
